/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultRouteImport } from './routes/result'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestRoomTestRoomIdRouteImport } from './routes/test-room.$testRoomId'
import { Route as DemoUploadRouteImport } from './routes/demo.upload'
import { Route as DemoSkillsRouteImport } from './routes/demo.skills'
import { Route as DemoRegisterRouteImport } from './routes/demo.register'
import { Route as DemoLoginRouteImport } from './routes/demo.login'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoomTestRoomIdRoute = TestRoomTestRoomIdRouteImport.update({
  id: '/test-room/$testRoomId',
  path: '/test-room/$testRoomId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoUploadRoute = DemoUploadRouteImport.update({
  id: '/demo/upload',
  path: '/demo/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSkillsRoute = DemoSkillsRouteImport.update({
  id: '/demo/skills',
  path: '/demo/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRegisterRoute = DemoRegisterRouteImport.update({
  id: '/demo/register',
  path: '/demo/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLoginRoute = DemoLoginRouteImport.update({
  id: '/demo/login',
  path: '/demo/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/result': typeof ResultRoute
  '/demo/login': typeof DemoLoginRoute
  '/demo/register': typeof DemoRegisterRoute
  '/demo/skills': typeof DemoSkillsRoute
  '/demo/upload': typeof DemoUploadRoute
  '/test-room/$testRoomId': typeof TestRoomTestRoomIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/result': typeof ResultRoute
  '/demo/login': typeof DemoLoginRoute
  '/demo/register': typeof DemoRegisterRoute
  '/demo/skills': typeof DemoSkillsRoute
  '/demo/upload': typeof DemoUploadRoute
  '/test-room/$testRoomId': typeof TestRoomTestRoomIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/result': typeof ResultRoute
  '/demo/login': typeof DemoLoginRoute
  '/demo/register': typeof DemoRegisterRoute
  '/demo/skills': typeof DemoSkillsRoute
  '/demo/upload': typeof DemoUploadRoute
  '/test-room/$testRoomId': typeof TestRoomTestRoomIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/result'
    | '/demo/login'
    | '/demo/register'
    | '/demo/skills'
    | '/demo/upload'
    | '/test-room/$testRoomId'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/result'
    | '/demo/login'
    | '/demo/register'
    | '/demo/skills'
    | '/demo/upload'
    | '/test-room/$testRoomId'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/result'
    | '/demo/login'
    | '/demo/register'
    | '/demo/skills'
    | '/demo/upload'
    | '/test-room/$testRoomId'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ResultRoute: typeof ResultRoute
  DemoLoginRoute: typeof DemoLoginRoute
  DemoRegisterRoute: typeof DemoRegisterRoute
  DemoSkillsRoute: typeof DemoSkillsRoute
  DemoUploadRoute: typeof DemoUploadRoute
  TestRoomTestRoomIdRoute: typeof TestRoomTestRoomIdRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-room/$testRoomId': {
      id: '/test-room/$testRoomId'
      path: '/test-room/$testRoomId'
      fullPath: '/test-room/$testRoomId'
      preLoaderRoute: typeof TestRoomTestRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/upload': {
      id: '/demo/upload'
      path: '/demo/upload'
      fullPath: '/demo/upload'
      preLoaderRoute: typeof DemoUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/skills': {
      id: '/demo/skills'
      path: '/demo/skills'
      fullPath: '/demo/skills'
      preLoaderRoute: typeof DemoSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/register': {
      id: '/demo/register'
      path: '/demo/register'
      fullPath: '/demo/register'
      preLoaderRoute: typeof DemoRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/login': {
      id: '/demo/login'
      path: '/demo/login'
      fullPath: '/demo/login'
      preLoaderRoute: typeof DemoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ResultRoute: ResultRoute,
  DemoLoginRoute: DemoLoginRoute,
  DemoRegisterRoute: DemoRegisterRoute,
  DemoSkillsRoute: DemoSkillsRoute,
  DemoUploadRoute: DemoUploadRoute,
  TestRoomTestRoomIdRoute: TestRoomTestRoomIdRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
